# Generated by Django 5.0 on 2024-01-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='no_of_coupons',
            field=models.IntegerField(default=10),
        ),
    ]
