# Generated by Django 5.0 on 2023-12-30 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_cart_items_cart'),
        ('products', '0005_product_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.product'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Cart_items',
        ),
    ]
