# Generated by Django 5.0 on 2023-12-30 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_cart_products_cart_items'),
        ('products', '0005_product_sub_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart_items',
            new_name='Cart_item',
        ),
        migrations.RenameField(
            model_name='cart_item',
            old_name='products',
            new_name='product',
        ),
    ]
