# Generated by Django 5.0 on 2024-01-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_cart_item_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='block',
            field=models.BooleanField(default=False),
        ),
    ]
