# Generated by Django 5.0 on 2024-01-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_cart_item_cart_alter_cart_item_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_item',
            name='is_added',
            field=models.BooleanField(default=False),
        ),
    ]
