# Generated by Django 5.0 on 2024-01-12 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_cart_item_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_item',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
