# Generated by Django 5.0 on 2024-01-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, null=True),
        ),
    ]
