# Generated by Django 5.0 on 2024-01-18 16:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_address_city_address_mobile_address_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='mobile',
        ),
        migrations.AddField(
            model_name='address',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Mobile number must be 10 digits.', regex='^\\d{10}$')]),
        ),
    ]
