# Generated by Django 5.0 on 2024-01-19 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_address_mobile_address_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='locality',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
