# Generated by Django 5.0 on 2024-01-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_order_ordered_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordered_item',
            name='price',
            field=models.BigIntegerField(),
        ),
    ]
