# Generated by Django 5.0 on 2024-01-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_ordered_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ordered_item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
