# Generated by Django 5.0 on 2024-01-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_order_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordered_item',
            name='price',
            field=models.FloatField(),
        ),
    ]
