# Generated by Django 5.0 on 2024-01-25 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_remove_profile_first_name_remove_profile_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordered_item',
            name='Ordered_product',
        ),
        migrations.AddField(
            model_name='ordered_item',
            name='ordered_product_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordered_item',
            name='unit_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=500),
        ),
    ]
