# Generated by Django 5.0 on 2024-01-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_my_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_coupon',
            name='is_applied',
            field=models.BooleanField(default=False),
        ),
    ]
