# Generated by Django 5.0 on 2024-01-26 05:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_my_coupon_is_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_coupon',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2024, 2, 25, 11, 1, 33, 534007)),
        ),
    ]
