# Generated by Django 5.0 on 2024-01-28 01:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_order_mob_order_name_alter_my_coupon_valid_till'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_coupon',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2024, 2, 27, 7, 6, 44, 721064)),
        ),
        migrations.AlterField(
            model_name='order',
            name='mob',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
