# Generated by Django 5.0 on 2024-01-28 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_alter_my_coupon_valid_till_alter_order_mob'),
    ]

    operations = [
        migrations.DeleteModel(
            name='My_coupon',
        ),
    ]
