# Generated by Django 5.0 on 2024-01-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_cart_applied_coupon_delete_my_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_discount',
            field=models.CharField(null=True),
        ),
    ]
