# Generated by Django 5.0 on 2024-01-30 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_ordered_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='subtotal',
            field=models.IntegerField(null=True),
        ),
    ]
