# Generated by Django 5.0 on 2024-02-05 06:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0061_order_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'deposit'), ('PURCHASED_PRODUCT', 'purchased product')], null=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.wallet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
