# Generated by Django 5.0 on 2024-02-07 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0062_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='block',
        ),
    ]
