# Generated by Django 5.0 on 2024-02-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0063_remove_profile_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='block',
            field=models.BooleanField(default=False),
        ),
    ]
