# Generated by Django 5.0 on 2024-02-10 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0064_profile_block'),
        ('products', '0011_productattribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_item',
            name='product_attribute',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='products.productattribute'),
        ),
    ]
