# Generated by Django 5.0 on 2024-02-12 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0067_alter_ordered_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordered_item',
            name='image',
            field=models.ImageField(max_length=300, null=True, upload_to='ordered_item'),
        ),
    ]
