# Generated by Django 5.0 on 2024-02-19 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0070_alter_wishlist_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordered_item',
            name='image',
        ),
    ]
