# Generated by Django 5.0 on 2024-02-19 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0071_remove_ordered_item_image'),
        ('products', '0012_alter_product_is_listed'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordered_item',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordered_items', to='products.product'),
        ),
    ]
