# Generated by Django 5.0 on 2024-02-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0072_ordered_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordered_item',
            name='product_variants',
            field=models.JSONField(null=True),
        ),
    ]
