# Generated by Django 5.0 on 2024-01-14 09:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='banners')),
                ('order', models.IntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
