# Generated by Django 5.0 on 2023-12-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_created_at_alter_category_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='starts_from',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
