# Generated by Django 5.0 on 2024-01-17 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_attributes_attribute_values_product_attributes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='attributes',
            field=models.ManyToManyField(through='products.ProductAttribute', to='products.attributes'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_attributes_attribute', to='products.attributes'),
        ),
    ]
