# Generated by Django 5.0 on 2024-02-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_attributes_attribute_values_product_attributes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='attribute',
        ),
        migrations.AddField(
            model_name='category',
            name='is_listed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_category_listed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='new_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_listed',
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='value',
        ),
        migrations.AddField(
            model_name='productattribute',
            name='value',
            field=models.ManyToManyField(related_name='product_attributes', to='products.attribute_values'),
        ),
    ]
