# Generated by Django 5.0 on 2024-01-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_category_is_listed_product_is_category_listed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='value',
        ),
        migrations.AddField(
            model_name='productattribute',
            name='value',
            field=models.ManyToManyField(related_name='product_attributes', to='products.attribute_values'),
        ),
    ]
