# Generated by Django 5.0 on 2024-02-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_productattribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_listed',
            field=models.BooleanField(default=False),
        ),
    ]
