# Generated by Django 5.0 on 2024-02-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_is_listed'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute_values',
            name='is_listed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='attributes',
            name='is_listed',
            field=models.BooleanField(default=True),
        ),
    ]
