# Generated by Django 5.0 on 2024-01-27 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_remove_productattribute_attribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute_values',
            name='Extra_price',
            field=models.IntegerField(null=True),
        ),
    ]
