# Generated by Django 5.0 on 2024-01-27 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_attribute_values_extra_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute_values',
            name='Extra_price',
        ),
        migrations.AddField(
            model_name='productattribute',
            name='Extra_price',
            field=models.IntegerField(null=True),
        ),
    ]
