# Generated by Django 5.0 on 2024-01-27 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_remove_attribute_values_extra_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productattribute',
            old_name='Extra_price',
            new_name='price',
        ),
    ]
