# Generated by Django 5.0 on 2024-01-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_remove_productattribute_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
