# Generated by Django 5.0 on 2024-01-27 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_productattribute_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productattribute',
            old_name='price',
            new_name='new_price',
        ),
    ]
